version: '3.8'

services:
  db:
    build:
      context: ./db/
      dockerfile: dockerfile
    image: db-image
    restart: always
    deploy:
      resources:
        limits:
            cpus: "0.75"
            memory: "512M"
        reservations:
            cpus: "0.40"
            memory: "128M"
    volumes:
      - ./db/mysql:/var/lib/mysql
    networks:
      - net
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=bill
      - MYSQL_PASSWORD=123
    expose:
      - 3306
      - 33060
    ports:
      - 81:3306
      - 82:33060

  nginx:
    build:
      context: ./nginx/
      dockerfile: dockerfile
    image: nginx-image
    restart: always
    deploy:
      resources:
         limits:
            cpus: "0.60"
            memory: "1024M"
         reservations:
            cpus: "0.40"
            memory: "512M"
    ports:
      - 80:80
    depends_on:
      - app
    networks:
      - net

  app:
    build:
      context: ./app/
      dockerfile: dockerfile
    image: app-image
    restart: always  
    deploy:
      resources:
         limits:
            cpus: "0.30"
            memory: "256M"
         reservations:
            cpus: "0.20"
            memory: "128M"
    ports:
      - 8080:8080
    networks:
      - net
    depends_on:
      - db

networks:
  net: