apiVersion: v1
kind: Ingress
metadata:
  name: ingress
  annotations:
     
spec:
  rules:
  - host: 
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: reverse-proxy
            port:
              name: http
