apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  replicas: 2
  serviceName: mysql
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      # terminationGracePeriodSeconds: 10
      containers:
        - name: mysql
          image: juliusandreas/db-image
          ports:
            - name: tpc
              protocol: TCP
              containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom: 
               secretKeyRef: 
                key: ROOT_PASSWORD
                name: mysecret
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
          resources:
            requests:
              storage: 1Gi
        # restartPolicy: Always
          volumes:
          - name: data
            persistentVolumeClaim:
              claimName: mysql-pvc
            
  # volumeClaimTemplates:
  #   - metadata:
  #       name: data
  #     spec:
  #       storageClassName: standard
  #       accessModes:
  #         - ReadWriteOnce
        